services:
  auth-app:
    build: ./client/
    ports:
      - 3000
    volumes:
      - ./client/:/client
      - /client/node_modules
      - ./config/.env.development.local:/client/.env.development.local:ro
    environment:
      - TZ=America/Toronto
  nginx:
    build: ./nginx/
    ports:
      - "${HOST_PORT}:${HOST_PORT}"
    environment:
      - HOST_NAME=${HOST_NAME}
      - HOST_PORT=${HOST_PORT}
    volumes:
      - ${SSL_CERTIFICATE_PASSPHRASE_PATH}:/etc/ssl/myserverssl-passphrase
      - ${SSL_CERTIFICATE_PATH}:/etc/ssl/certs/myserverssl.cer
      - ${SSL_CERTIFICATE_KEY_PATH}:/etc/ssl/private/myserverssl.key
    depends_on:
      - auth-app
